version: "3.9"
services:
  # PostgreSQL Database Service
  db:
    container_name: react_express_pg_db
    image: postgres:13
    ports:
      - "5432:5432" # Expose PostgreSQL on default port
    environment:
      POSTGRES_USER: admin # PostgreSQL User
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: react_express_db
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data in a volume
    restart: unless-stopped # Restart automatically unless manually stopped

volumes:
  db_data: # Declare the named volume
